image: alpine/3.12
sources:
  - https://github.com/voutilad/virtio_vmmci
packages:
  - gcc
  - make
tasks:
  - setup: |
      sudo apk add linux-$(uname -r | awk -F '-' '{ print $3 }')-dev
  - build: |
      cd virtio_vmmci
      make
